

export const RouteNames = Object.freeze({
  GETTING_STARTED_SCREEN: "[App]GettingStarted",
  SIGNUP_SCREEN: "[App]Signup",
  SIGNIN_SCREEN: "[App]Signin",

});


export const SCREEN_OPTIONS_COLOR = {
  ALLMEMBER_BG: "#EAA250",
  MANAGE_NEWS_BG: "#3448FF",
  MANAGE_REQUESTS_BG: "#FF3972",
  MANAGE_GALLERY_BG: "#5B6EA2",
  VILLAGE_OFFICIALS_BG: "#9DCB90",
  SARPANCH_MESSAGES_BG: "#DD7F66",
  MANAGE_VILLAGE: "#9DCBCC",
  LIVE: "#FF0000",
  BLUE: "#80c5ec",
  MEETING: "#d180c2",
};


